# Generated by Django 4.2.3 on 2023-08-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddBid',
            new_name='Bids',
        ),
    ]
